###SET COUNTRY ID ----
CORN_1=CHN_CORN
CORN_2=JPN_CORN
CORN_3=KOR_CORN
CORN_4=MEX_CORN
CORN_5=EUN_CORN
CORN_6=ROW_CORN
CORN_7=USA_CORN
CORN_8=ARG_CORN
CORN_9=BRA_CORN
CORN_10=UKR_CORN
CORN_11=IND_CORN
CORN_12=RUS_CORN

BE_1=CHN_BE
BE_2=EUN_BE
BE_3=ROW_BE
BE_4=USA_BE
BE_5=BRA_BE
BE_6=IND_BE

###BASE YEAR: LAST ROW ----
#BASE YEAR VALUE ----
#CORN
for(i in 1:12){
  assign(paste0('CORN_BY_',i,sep=''),tail(get(paste('CORN_',i,sep='')),1))
}
#IMP COUNTRIES
CORN_BY_IMP=rbind(CORN_BY_1,CORN_BY_2,CORN_BY_3,CORN_BY_4,CORN_BY_5,CORN_BY_6)
rownames(CORN_BY_IMP)=c("CHN","JPN","KOR","MEX","EUN","ROW")
CORN_BY_IMP[is.na(CORN_BY_IMP)] <- 0

#EXP COUNTRIES
CORN_BY_EXP=rbind(CORN_BY_7,CORN_BY_8,CORN_BY_9,CORN_BY_10,CORN_BY_11,CORN_BY_12)
rownames(CORN_BY_EXP)=c("USA","ARG","BRA","UKR","IND","RUS")
CORN_BY_EXP[is.na(CORN_BY_EXP)] <- 0
NETIMP<--CORN_BY_EXP$NETEXP
CORN_BY_EXP=CORN_BY_EXP[,-16]
CORN_BY_EXP=cbind(CORN_BY_EXP,NETIMP)
#ALL COUNTRIES
CORN_BY=rbind(CORN_BY_IMP,CORN_BY_EXP)

#BE
for(i in 1:6){
  assign(paste0('BE_BY_',i,sep=''),tail(get(paste('BE_',i,sep='')),1))
}
#IMP COUNTRIES
BE_BY_IMP=rbind(BE_BY_1,BE_BY_2,BE_BY_3)
rownames(BE_BY_IMP)=c("CHN","EUN","ROW")
BE_BY_IMP[is.na(BE_BY_IMP)] <- 0
#EXP COUNTRIES
BE_BY_EXP=rbind(BE_BY_4,BE_BY_5,BE_BY_6)
rownames(BE_BY_EXP)=c("USA","BRA","IND")
BE_BY_EXP[is.na(BE_BY_EXP)] <- 0
NETIMP<--BE_BY_EXP$NETEXP
BE_BY_EXP=BE_BY_EXP[,-9]
BE_BY_EXP=cbind(BE_BY_EXP,NETIMP)
#ALL COUNTRIES
BE_BY=rbind(BE_BY_IMP,BE_BY_EXP)
#MATRIX ----
CORN_AA_BY=data.matrix(CORN_BY$AA)
CORN_YD_BY=data.matrix(CORN_BY$YD)
CORN_FOOD_BY=data.matrix(CORN_BY$FOOD)
CORN_FEED_BY=data.matrix(CORN_BY$FEED)
CORN_LOSS_BY=data.matrix(CORN_BY$LOSS)
CORN_SEED_BY=data.matrix(CORN_BY$SEED)
CORN_CSTV_BY=data.matrix(CORN_BY$STV)
CORN_PROC_BY=data.matrix(CORN_BY$PROC)

BE_PD_BY=data.matrix(BE_BY$PD)
BE_DM_BY=data.matrix(BE_BY$DM)
BE_BESTV_BY=data.matrix(BE_BY$STV)
###BASE YEAR: 2ND LAST ROW ----
#VALUE ----
#CORN
#No. of rows
row=nrow(CORN_1)
for(i in 1:12){
  assign(paste0('CORN_LBY_',i,sep=''),get(paste('CORN_',i,sep=''))[row-1,])
}
#IMP COUNTRIES
CORN_LBY_IMP=rbind(CORN_LBY_1,CORN_LBY_2,CORN_LBY_3,CORN_LBY_4,CORN_LBY_5,CORN_LBY_6)
rownames(CORN_LBY_IMP)=c("CHN","JPN","KOR","MEX","EUN","ROW")
CORN_LBY_IMP[is.na(CORN_LBY_IMP)] <- 0
#EXP COUNTRIES
CORN_LBY_EXP=rbind(CORN_LBY_7,CORN_LBY_8,CORN_LBY_9,CORN_LBY_10,CORN_LBY_11,CORN_LBY_12)
rownames(CORN_LBY_EXP)=c("USA","ARG","BRA","UKR","IND","RUS")
CORN_LBY_EXP[is.na(CORN_LBY_EXP)] <- 0
NETIMP<--CORN_LBY_EXP$NETEXP
CORN_LBY_EXP=CORN_LBY_EXP[,-16]
CORN_LBY_EXP=cbind(CORN_LBY_EXP,NETIMP)
#ALL COUNTRIES
CORN_LBY=rbind(CORN_LBY_IMP,CORN_LBY_EXP)
#MATRIX ----
CORN_YD_LBY=data.matrix(CORN_LBY$YD)
###CALIBRATION ----
i=0 # FOR CALIBRATION
#EXO. VARIALBES
RICEP=data.matrix(RICEP_S0[i+gap,2:13])
WHEAP=data.matrix(WHEAP_S0[i+gap,2:13])
SOYBP=data.matrix(SOYBP_S0[i+gap,2:13])
OTHGP=data.matrix(OTHGP_S0[i+gap,2:13])
PINC=data.matrix(PGDP_S0[i+gap,2:13])
PGDP=data.matrix(PGDP_S0[i+gap,2:13])
POP=data.matrix(POP_S0[i+gap,2:13])
PORK_PD=data.matrix(PORKPD_S0[i+gap,2:13])
BEEF_PD=data.matrix(BEEFPD_S0[i+gap,2:13])
POUT_PD=data.matrix(POUTPD_S0[i+gap,2:13])
MILK_PD=data.matrix(MILKPD_S0[i+gap,2:13])
GMO_AA=data.matrix(GMO_AA_S0[i+gap,2:13])
GMO_YD=data.matrix(GMO_YD_S0[i+gap,2:13])

STVCN=data.matrix(CSTV_S0[i+gap,2:13])
FERP=data.matrix(FERP_S0[i+gap,2:13])
OILP=data.matrix(OILPBE_S0[i+gap,2:7])
PGDPBE=data.matrix(PGDPBE_S0[i+gap,2:7])
##CALIBRATION: CONSTANT TERMS ----
#PRICES 
I=matrix(1,12,1)
CORN_PRICE_PCS=PWD_CORN*data.matrix(CORN_PRICE$EXCH)*(I+data.matrix(CORN_PRICE$DUTY)/100)
CORN_PRICE_PPD=CORN_PRICE_PCS+data.matrix(CORN_PRICE$MI)*data.matrix(CORN_PRICE$EXCH)
CORN_PRICE_ALL=cbind(CORN_PRICE_PCS,CORN_PRICE_PPD)
CORN_PRICE_PCS=data.matrix(CORN_PRICE_ALL[,1])
CORN_PRICE_PPD=data.matrix(CORN_PRICE_ALL[,2])
BE_PRICE_CORN=data.matrix(CORN_PRICE_PCS[c(1,5,6,7,9,11),1])
BE_PRICE_BE_ALL=PWD_BE_ALL*data.matrix(CORN_PRICE$EXCH)
BE_PRICE_BE=data.matrix(BE_PRICE_BE_ALL[c(1,5,6,7,9,11),1])
#AA/LOSS/SEED 
LNAA=CORN_AA_PPD*log(CORN_PRICE_PPD)+CORN_AA_RCE*t(log(RICEP))+CORN_AA_WHT*t(log(WHEAP))+CORN_AA_SYB*t(log(SOYBP))+CORN_AA_CG*t(log(OTHGP))+CORN_AA_FER*t(log(FERP))
LOSS=CORN_LOSSRATE*CORN_AA_BY
SEED=CORN_SEEDRATE*CORN_AA_BY
#YD 
#YD=data.matrix(CORN_YD_LBY)*(1+CORN_YD_TECH)
#FOOD 
LNPFOOD=CORN_PFOOD_PCS*log(CORN_PRICE_PCS)+CORN_PFOOD_RCE*t(log(RICEP))+CORN_PFOOD_WHT*t(log(WHEAP))+CORN_PFOOD_CG*t(log(OTHGP))+CORN_PFOOD_PINC*t(log(PINC))
FEED=CORN_FEED_PDPK*t(PORK_PD)+CORN_FEED_PDBF*t(BEEF_PD)+CORN_FEED_PDPT*t(POUT_PD)+CORN_FEED_PDMK*t(MILK_PD)
#CSTV 
CSTV=CORN_CSTV_BY
#PD 
CORNP=data.matrix(BE_PRICE_CORN)
BEP=data.matrix(BE_PRICE_BE)
LNPD=BE_PD_POIL*t(log(OILP))+BE_PD_PMZ*log(CORNP)+BE_PD_PBE*log(BEP)
#DM ----
LNDM=BE_DM_POIL*t(log(OILP))+BE_DM_PBE*log(BEP)+BE_DM_PGDP*t(log(PGDPBE))
#PROD ----
PROC=exp(CORN_PROC_PGDP*t(log(PGDP)))
PROC[1]=PROC[1]+BE_PD_BY[1]/300*100*0.7
PROC[5]=PROC[5]+BE_PD_BY[2]/400*100*0.5
PROC[6]=PROC[6]+BE_PD_BY[3]/400*100*0.5
PROC[7]=PROC[7]+BE_PD_BY[4]/400*100*0.58
#BESTV 
BESTV=BE_BESTV_BY

PFOOD=CORN_FOOD_BY/t(data.matrix(POP))*1000

A_LNAA=log(CORN_AA_BY)-LNAA
#A_YD=CORN_YD_BY-YD
A_LNPFOOD=log(PFOOD)-LNPFOOD
A_PROC=CORN_PROC_BY-PROC
A_FEED=CORN_FEED_BY-FEED
A_SEED=CORN_SEED_BY-SEED
A_LOSS=CORN_LOSS_BY-LOSS
A_CSTV=CORN_CSTV_BY-CSTV
A_LNPD=log(BE_PD_BY)-LNPD
A_LNDM=log(BE_DM_BY)-LNDM
A_BESTV=BE_BESTV_BY-BESTV

CHECK_AA=exp(A_LNAA+CORN_AA_PPD*log(CORN_PRICE_PPD)+CORN_AA_RCE*t(log(RICEP))+CORN_AA_WHT*t(log(WHEAP))+CORN_AA_SYB*t(log(SOYBP))+CORN_AA_CG*t(log(OTHGP))+CORN_AA_FER*t(log(FERP)))-CORN_AA_BY
#CHECK_YD=A_YD+CORN_YD_LBY*(1+CORN_YD_TECH)-CORN_YD_BY
CHECK_FOOD=exp(A_LNPFOOD+CORN_PFOOD_PCS*log(CORN_PRICE_PCS)+CORN_PFOOD_RCE*t(log(RICEP))+CORN_PFOOD_WHT*t(log(WHEAP))+CORN_PFOOD_CG*t(log(OTHGP))+CORN_PFOOD_PINC*t(log(PINC)))*t(POP)/1000-CORN_FOOD_BY
CHECK_FEED=A_FEED+CORN_FEED_PDPK*t(PORK_PD)+CORN_FEED_PDBF*t(BEEF_PD)+CORN_FEED_PDPT*t(POUT_PD)+CORN_FEED_PDMK*t(MILK_PD)-CORN_FEED_BY
CHECK_LOSS=A_LOSS+CORN_LOSSRATE*CORN_AA_BY-CORN_LOSS_BY
CHECK_SEED=A_SEED+CORN_SEEDRATE*CORN_AA_BY-CORN_SEED_BY
CHECK_CSTV=A_CSTV+CORN_CSTV_BY-CORN_CSTV_BY
CORNP=data.matrix(BE_PRICE_CORN)
BEP=data.matrix(BE_PRICE_BE)
CHECK_PD=exp(A_LNPD+BE_PD_POIL*t(log(OILP))+BE_PD_PMZ*log(CORNP)+BE_PD_PBE*log(BEP))-BE_PD_BY
CHECK_DM=exp(A_LNDM+BE_DM_POIL*t(log(OILP))+BE_DM_PBE*log(BEP)+BE_DM_PGDP*t(log(PGDPBE)))-BE_DM_BY
CHECK_BESTV=A_BESTV+BE_BESTV_BY-BE_BESTV_BY

CHECK_PROC=A_PROC+exp(CORN_PROC_PGDP*t(log(PGDP)))-CORN_PROC_BY
CHECK_PROC=A_PROC+exp(CORN_PROC_PGDP*t(log(PGDP)))-CORN_PROC_BY
CHECK_PROC[1]=CHECK_PROC[1]+BE_PD_BY[1]/300*100*0.7
CHECK_PROC[5]=CHECK_PROC[5]+BE_PD_BY[2]/400*100*0.5
CHECK_PROC[6]=CHECK_PROC[6]+BE_PD_BY[3]/400*100*0.5
CHECK_PROC[7]=CHECK_PROC[7]+BE_PD_BY[4]/400*100*0.58

